// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgesxxasvxsoushcgyou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnZXN4eGFzdnhzb3VzaGNneW91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NzU1MTUsImV4cCI6MjA1OTM1MTUxNX0.QmFhRhOa8lHOrotzhXc8Y4PMfyV9VO0UDszu1G4YPXw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);